In [1]:
import numpy as np

In [17]:
a = np.arange(0,10)
a.reshape(-1,5) 
a.reshape(2,5)
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
b = np.arange(3,7)
c = b[[0,1,3,2]]
c

array([3, 4, 6, 5])

In [33]:
label = [0,0,1,1,2,2]
num_sample = 6
classes = 3
y = np.zeros((num_sample,classes))
row = 0 
for i in label:
    

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [21]:
import numpy as np 
a = np.array([[2,5,8],[3,4,1]])
a_power = np.power(np.e,a)
a_power_2 = np.power(np.exp(a),1)
np.argmin(a_power,axis=0),np.argmin(a_power,axis=1),a_power,a_power_2
# Convert the flat index to row and column indices
# min_index = np.unravel_index(min_index_flat, a_power.shape)

# Print the result
# print("Index of minimum value:", min_index)
# print("Minimum value:", a_power[min_index])

(array([0, 1, 1], dtype=int64),
 array([0, 2], dtype=int64),
 array([[7.38905610e+00, 1.48413159e+02, 2.98095799e+03],
        [2.00855369e+01, 5.45981500e+01, 2.71828183e+00]]),
 array([[7.38905610e+00, 1.48413159e+02, 2.98095799e+03],
        [2.00855369e+01, 5.45981500e+01, 2.71828183e+00]]))

In [25]:
b = np.array([[0,1,2],
              [0,0,0]])
np.sum(b,axis = 0)

array([0, 1, 2])