In [1]:
from my_lib import *


In [2]:
vector = np. array ([ -2 , 4 , 9 , 21])
compute_vector_length ([ vector ])

23.280893453645632

In [3]:
v1 = np. array ([0 , 1 , -1 , 2])
v2 = np. array ([2 , 5 , 1 , 0])
compute_dot_product(v1,v2)

4

In [8]:
x = np. array ([[-1 , 2] ,
            [3 , -4]])
k = np. array ([1 , 2])
print ('result \n', x@k )

result 
 [ 3 -5]


In [9]:
m = np. array ([[ -1 , 1 , 1] , [0 , -4 , 9]])
v = np. array ([0 , 2 , 1])
matrix_multi_vector (m, v)

array([3, 1])

In [10]:
m1 = np. array ([[0 , 1 , 2] , [2 , -3 , 1]])
m2 = np. array ([[1 , -3] ,[6 , 1] , [0 , -1]])
matrix_multi_matrix (m1 , m2)

array([[  6,  -1],
       [-16, -10]])

In [11]:
m1 = np.eye (3)
m2 = np. array ([[1 , 1 , 1] ,[2 , 2 , 2] , [3 , 3 , 3]])
m1@m2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [12]:
m1 = np.eye (2)
m1 = np. reshape (m1 ,( -1 ,4) ) [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
m1@m2

array([5., 5., 5., 5.])

In [13]:
m1 = np. array ([[ -2 , 6] , [8 , -4]])
inverse_matrix (m1)

array([[0.1 , 0.15],
       [0.2 , 0.05]])

In [14]:
matrix = np. array ([[0.9 , 0.2] , [0.1 , 0.8]])
eigenvalues , eigenvectors = compute_eigenvalues_eigenvectors ( matrix )
print ( eigenvectors )

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [15]:
x = np. array ([1 , 2 , 3 , 4])
y = np. array ([1 , 0 , 3 , 0])
result = compute_cosine (x,y)
print( round (result , 3) )

0.577
